# Generated by Django 3.0.3 on 2023-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230518_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoint_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
