# Generated by Django 3.0.3 on 2023-05-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20230515_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patimage',
            field=models.ImageField(default=False, upload_to='Patient'),
        ),
    ]
