# Generated by Django 3.0.3 on 2023-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20230515_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='docimage',
            field=models.ImageField(default='Patient/default.png', upload_to='Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patimage',
            field=models.ImageField(default='Patient/default.png', upload_to='Patient'),
        ),
    ]
