# Generated by Django 3.0.3 on 2023-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20230515_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='docimage',
            field=models.ImageField(default='media/Doctor/default.png', upload_to='media/Doctor/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patimage',
            field=models.ImageField(default='media/Patient/default.png', upload_to='media/Patient'),
        ),
    ]
