# Generated by Django 3.0.3 on 2023-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20230515_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patimage',
            field=models.ImageField(default='media/Patient/default.png', upload_to='media/'),
        ),
    ]
