# Generated by Django 3.0.3 on 2023-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20230515_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='docimage',
            field=models.ImageField(default='media/Doctor/default.png', upload_to='media/'),
        ),
    ]
